apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app: xds-server
      app.kubernetes.io/name: xds-server
      app.kubernetes.io/version: 4ed1298
      app.kubernetes.io/managed-by: kubectl
    includeSelectors: false

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: xds-server-env
    envs:
      - params.env

# We need to disable suffix if we migrate to knative services
# currently knative does not recognize configmaps with suffix hash
# generatorOptions:
#   disableNameSuffixHash: true

images:
  - name: zjuici/xds-server
    newName: weekenthralling/xds-server
    newTag: 4ed1298
